name = "TraceableAgency"
version = "4.0.0"
keywords = ["math", "decision-theory", "information-theory", "formal-verification"]
defaultTargets = ["TraceableAgency"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
weak.linter.defProp = false
weak.linter.overlappingInstances = false
weak.linter.unnecessarySimpa = false
weak.linter.unusedSectionVars = false
weak.linter.unusedSimpArgs = false
weak.linter.unusedVariables = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.1"

[[lean_lib]]
name = "TraceableAgency"
