#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source_file="$script_dir/trace_tempered_choice_v3.tex"
target_file="$script_dir/theorem1_pure_trace_appendix.tex"
temporary_file=$(mktemp "$script_dir/.theorem1_pure_trace_appendix.XXXXXX")

cleanup() {
  rm -f -- "$temporary_file"
}
trap cleanup EXIT HUP INT TERM

awk '
BEGIN {
  print "% Generated from the leanpurestatement and leanpureproof regions of"
  print "% trace_tempered_choice_v3.tex.  Run extract_lean_faithful_pure_trace.sh"
  print "% after editing either marked region; do not edit this file by hand."
  print ""
}
$0 == "%<*leanpurestatement>" { copying = 1; next }
$0 == "%</leanpurestatement>" { copying = 0; print ""; next }
$0 == "%<*leanpureproof>" { copying = 1; next }
$0 == "%</leanpureproof>" { copying = 0; next }
copying { print }
' "$source_file" > "$temporary_file"

mv -- "$temporary_file" "$target_file"
trap - EXIT HUP INT TERM
